import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Navbar from "@/components/Navbar";
import RootLoader from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-8xl mx-auto">
          <div className="flex flex-col h-screen">
            <Navbar />
            <div className="mt-12 mx-auto flex items-center justify-center">
              <Suspense fallback={<RootLoader />}>{children}</Suspense>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
